inherit_from: base_rubocop.yml

require: rubocop-rspec

Layout/MultilineOperationIndentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/codeclimate-rubocop'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
